# Generated by Django 5.0.2 on 2025-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.CharField(default='TEST', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
