# Generated by Django 5.0.2 on 2025-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
