# Generated by Django 5.0.2 on 2025-04-23 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documentupdate_documentview'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
