# Generated by Django 5.0.2 on 2025-04-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_doc_uuid_document_is_public'),
        ('document', '0004_alter_document_link'),
    ]

    operations = [
    ]
