# Generated by Django 5.0.2 on 2025-04-25 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_document_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='default_access_level',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Owner'), (3, 'Admin'), (2, 'Writer'), (1, 'Read_Only'), (0, 'Deny')], default=2),
        ),
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(4, 'Owner'), (3, 'Admin'), (2, 'Writer'), (1, 'Read_Only'), (0, 'Deny')], default=2)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
