# Generated by Django 5.0.2 on 2025-04-25 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_default_access_level_accesslevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesslevel',
            unique_together={('user', 'document')},
        ),
    ]
