# Generated by Django 5.0.2 on 2025-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_accesslevel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Owner'), (3, 'Admin'), (2, 'Writer'), (1, 'ReadOnly'), (0, 'Deny')], default=2),
        ),
    ]
