# Generated by Django 5.0.2 on 2025-04-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_merge_20250424_1643'),
        ('document', '0007_alter_accesslevel_access_level'),
    ]

    operations = [
    ]
