# Generated by Django 5.0.2 on 2025-05-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_merge_20250425_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='سند بدون عنوان', max_length=255),
        ),
    ]
