# Generated by Django 5.0.2 on 2025-05-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_comment_commentreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_premission_access',
            field=models.BooleanField(default=True),
        ),
    ]
