# Generated by Django 5.0.2 on 2025-05-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_document_public_premission_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='range_end',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='range_start',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
