# Generated by Django 5.0.2 on 2025-05-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_alter_comment_range_end_alter_comment_range_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
