# Generated by Django 5.0.2 on 2025-05-20 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_alter_comment_range_end_alter_comment_range_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupdate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentupdate',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='compacted_document_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentupdate',
            name='is_compacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentupdate',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentupdate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
