# Generated by Django 5.0.2 on 2025-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_comment_commentreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='documentupdate',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
