# Generated by Django 5.0.2 on 2025-08-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_remove_document_content_documentupdate_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupdate',
            name='page',
        ),
    ]
