version: '3.9'
services:
  backend:
    build: 
      context: ..
      dockerfile: Dockerfile
    command: ./backend-entrypoint.sh
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=iransanad.settings
      - DEBUG=0

    restart: always
    volumes:
      - ..:/app
      - /var/www/iransanad:/var/www/iransanad
    depends_on:
      - db

  db:
    image: postgres:16

    env_file:
      - postgres/.env


    restart: always

    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  celery:
    build: 
      context: ..
      dockerfile: Dockerfile
    command: celery -A iransanad worker -l info
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis

  celery_beat:
    build: 
      context: ..
      dockerfile: Dockerfile
    command: celery -A iransanad beat -l info
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis

  flower:
    build: 
      context: ..
      dockerfile: Dockerfile
    command: celery -A iransanad flower
    ports:
      - 5555:5555
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
