# Generated by Django 5.0.2 on 2025-05-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_verified_emailverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
